function is_bayer = ps_is_bayer(format)
% PS_IS_BAYER True if format string indicates Bayer tiled array.
%   PS_IS_BAYER(format) returns true if format string describes any of
%   available Bayer tile formats.
%
%   format is a string describing the image data pixel format, see
%   BatchAcquisition.h header for details of all available formats.
%   Only a subset of Bayer formats is supported.
%
%   See also PS_DEMOSAIC, PS_CREATE_RAW_DATA_MATRIX, PS_IS_GRAY.

% $Revision: 1.2 $  $Date: 2017/08/09 $
% $Author(s): Tomislav Petkovic $

narginchk(1, 1);
nargoutchk(0, 1);

assert( ischar(format) );

bayer_formats = { ...
    'IDT_8U_BayerGR', ...
    'IDT_8U_BayerRG', ...
    'IDT_8U_BayerGB', ...
    'IDT_8U_BayerBG', ...
    'IDT_12U_BayerGR_Packed', ...
    'IDT_12U_BayerRG_Packed', ...
    'IDT_12U_BayerGB_Packed', ...
    'IDT_12U_BayerBG_Packed', ...
    'IDT_16U_BayerGR', ...
    'IDT_16U_BayerRG', ...
    'IDT_16U_BayerGB', ...
    'IDT_16U_BayerBG', ...
    'IDT_16U_BayerGR_BigEndian', ...
    'IDT_16U_BayerRG_BigEndian', ...
    'IDT_16U_BayerGB_BigEndian', ...
    'IDT_16U_BayerBG_BigEndian', ...
    'IDT_32F_BayerGR', ...
    'IDT_32F_BayerRG', ...
    'IDT_32F_BayerGB', ...
    'IDT_32F_BayerBG', ...
    'IDT_64F_BayerGR', ...
    'IDT_64F_BayerRG', ...
    'IDT_64F_BayerGB', ...
    'IDT_64F_BayerBG' ...
    };

is_bayer = any( strcmpi(format, bayer_formats) );
